### ISSUE TITLE
Generalize filter_all and clean_all with list of steps and Python's reduce

### ISSUE THREAD

**Issue by p16i** [wannaphong/Thai-Data-Privacy#1]
In some situation, one might want to only filter or clean a subset of tokens (e.g. name and phone no.). We might generalize the functions such as`filter_all` and `clean_all` to be something like 
```
def filters(text, steps=[filter_func1, filter_func_2, ...]):
...
```

To execute a chain of functions, we can also use Python's `reduce`.  For example, one simply does

```
out = functools.reduce(lambda x, y : y(x), [f1, f2, f3, f4], text)
```

See also: https://stackoverflow.com/a/20454187

References:
https://github.com/wannaphong/Thai-Data-Privacy/blob/master/thaidp/filter.py#L49
https://github.com/wannaphong/Thai-Data-Privacy/blob/master/thaidp/clean.py#L43

**Comment by wannaphong** [comment]
Thank you.
